import { Country } from './models';

export const countries: Country[] = [
    { name: 'Afghanistan', code: 'AF', vatPrefix: null },
    { name: 'Åland Islands', code: 'AX', vatPrefix: null },
    { name: 'Albania', code: 'AL', vatPrefix: null },
    { name: 'Algeria', code: 'DZ', vatPrefix: null },
    { name: 'American Samoa', code: 'AS', vatPrefix: null },
    { name: 'Andorra', code: 'AD', vatPrefix: null },
    { name: 'Angola', code: 'AO', vatPrefix: null },
    { name: 'Anguilla', code: 'AI', vatPrefix: null },
    { name: 'Antarctica', code: 'AQ', vatPrefix: null },
    { name: 'Antigua and Barbuda', code: 'AG', vatPrefix: null },
    { name: 'Argentina', code: 'AR', vatPrefix: null },
    { name: 'Armenia', code: 'AM', vatPrefix: null },
    { name: 'Aruba', code: 'AW', vatPrefix: null },
    { name: 'Australia', code: 'AU', vatPrefix: null },
    { name: 'Austria', code: 'AT', vatPrefix: 'AT' },
    { name: 'Azerbaijan', code: 'AZ', vatPrefix: null },
    { name: 'Bahamas', code: 'BS', vatPrefix: null },
    { name: 'Bahrain', code: 'BH', vatPrefix: null },
    { name: 'Bangladesh', code: 'BD', vatPrefix: null },
    { name: 'Barbados', code: 'BB', vatPrefix: null },
    { name: 'Belarus', code: 'BY', vatPrefix: null },
    { name: 'Belgium', code: 'BE', vatPrefix: 'BE' },
    { name: 'Belize', code: 'BZ', vatPrefix: null },
    { name: 'Benin', code: 'BJ', vatPrefix: null },
    { name: 'Bermuda', code: 'BM', vatPrefix: null },
    { name: 'Bhutan', code: 'BT', vatPrefix: null },
    { name: 'Bolivia', code: 'BO', vatPrefix: null },
    { name: 'Bosnia and Herzegovina', code: 'BA', vatPrefix: null },
    { name: 'Botswana', code: 'BW', vatPrefix: null },
    { name: 'Bouvet Island', code: 'BV', vatPrefix: null },
    { name: 'Brazil', code: 'BR', vatPrefix: null },
    { name: 'British Indian Ocean Territory', code: 'IO', vatPrefix: null },
    { name: 'Brunei Darussalam', code: 'BN', vatPrefix: null },
    { name: 'Bulgaria', code: 'BG', vatPrefix: 'BG' },
    { name: 'Burkina Faso', code: 'BF', vatPrefix: null },
    { name: 'Burundi', code: 'BI', vatPrefix: null },
    { name: 'Cambodia', code: 'KH', vatPrefix: null },
    { name: 'Cameroon', code: 'CM', vatPrefix: null },
    { name: 'Canada', code: 'CA', vatPrefix: null },
    { name: 'Cape Verde', code: 'CV', vatPrefix: null },
    { name: 'Cayman Islands', code: 'KY', vatPrefix: null },
    { name: 'Central African Republic', code: 'CF', vatPrefix: null },
    { name: 'Chad', code: 'TD', vatPrefix: null },
    { name: 'Chile', code: 'CL', vatPrefix: null },
    { name: 'China', code: 'CN', vatPrefix: null },
    { name: 'Christmas Island', code: 'CX', vatPrefix: null },
    { name: 'Cocos (Keeling) Islands', code: 'CC', vatPrefix: null },
    { name: 'Colombia', code: 'CO', vatPrefix: null },
    { name: 'Comoros', code: 'KM', vatPrefix: null },
    { name: 'Congo', code: 'CG', vatPrefix: null },
    { name: 'Congo, The Democratic Republic of the', code: 'CD', vatPrefix: null },
    { name: 'Cook Islands', code: 'CK', vatPrefix: null },
    { name: 'Costa Rica', code: 'CR', vatPrefix: null },
    { name: 'Cote D\'Ivoire', code: 'CI', vatPrefix: null },
    { name: 'Croatia', code: 'HR', vatPrefix: 'HR' },
    { name: 'Cuba', code: 'CU', vatPrefix: null },
    { name: 'Cyprus', code: 'CY', vatPrefix: 'CY' },
    { name: 'Czech Republic', code: 'CZ', vatPrefix: 'CZ' },
    { name: 'Denmark', code: 'DK', vatPrefix: 'DK' },
    { name: 'Djibouti', code: 'DJ', vatPrefix: null },
    { name: 'Dominica', code: 'DM', vatPrefix: null },
    { name: 'Dominican Republic', code: 'DO', vatPrefix: null },
    { name: 'Ecuador', code: 'EC', vatPrefix: null },
    { name: 'Egypt', code: 'EG', vatPrefix: null },
    { name: 'El Salvador', code: 'SV', vatPrefix: null },
    { name: 'Equatorial Guinea', code: 'GQ', vatPrefix: null },
    { name: 'Eritrea', code: 'ER', vatPrefix: null },
    { name: 'Estonia', code: 'EE', vatPrefix: 'EE' },
    { name: 'Ethiopia', code: 'ET', vatPrefix: null },
    { name: 'Falkland Islands (Malvinas)', code: 'FK', vatPrefix: null },
    { name: 'Faroe Islands', code: 'FO', vatPrefix: null },
    { name: 'Fiji', code: 'FJ', vatPrefix: null },
    { name: 'Finland', code: 'FI', vatPrefix: 'FI' },
    { name: 'France', code: 'FR', vatPrefix: 'FR' },
    { name: 'French Guiana', code: 'GF', vatPrefix: null },
    { name: 'French Polynesia', code: 'PF', vatPrefix: null },
    { name: 'French Southern Territories', code: 'TF', vatPrefix: null },
    { name: 'Gabon', code: 'GA', vatPrefix: null },
    { name: 'Gambia', code: 'GM', vatPrefix: null },
    { name: 'Georgia', code: 'GE', vatPrefix: null },
    { name: 'Germany', code: 'DE', vatPrefix: 'DE' },
    { name: 'Ghana', code: 'GH', vatPrefix: null },
    { name: 'Gibraltar', code: 'GI', vatPrefix: null },
    { name: 'Greece', code: 'GR', vatPrefix: 'EL' },
    { name: 'Greenland', code: 'GL', vatPrefix: null },
    { name: 'Grenada', code: 'GD', vatPrefix: null },
    { name: 'Guadeloupe', code: 'GP', vatPrefix: null },
    { name: 'Guam', code: 'GU', vatPrefix: null },
    { name: 'Guatemala', code: 'GT', vatPrefix: null },
    { name: 'Guernsey', code: 'GG', vatPrefix: null },
    { name: 'Guinea', code: 'GN', vatPrefix: null },
    { name: 'Guinea-Bissau', code: 'GW', vatPrefix: null },
    { name: 'Guyana', code: 'GY', vatPrefix: null },
    { name: 'Haiti', code: 'HT', vatPrefix: null },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM', vatPrefix: null },
    { name: 'Holy See (Vatican City State)', code: 'VA', vatPrefix: null },
    { name: 'Honduras', code: 'HN', vatPrefix: null },
    { name: 'Hong Kong', code: 'HK', vatPrefix: null },
    { name: 'Hungary', code: 'HU', vatPrefix: 'HU' },
    { name: 'Iceland', code: 'IS', vatPrefix: null },
    { name: 'India', code: 'IN', vatPrefix: null },
    { name: 'Indonesia', code: 'ID', vatPrefix: null },
    { name: 'Iran, Islamic Republic Of', code: 'IR', vatPrefix: null },
    { name: 'Iraq', code: 'IQ', vatPrefix: null },
    { name: 'Ireland', code: 'IE', vatPrefix: 'IE' },
    { name: 'Isle of Man', code: 'IM', vatPrefix: null },
    { name: 'Israel', code: 'IL', vatPrefix: null },
    { name: 'Italy', code: 'IT', vatPrefix: 'IT' },
    { name: 'Jamaica', code: 'JM', vatPrefix: null },
    { name: 'Japan', code: 'JP', vatPrefix: null },
    { name: 'Jersey', code: 'JE', vatPrefix: null },
    { name: 'Jordan', code: 'JO', vatPrefix: null },
    { name: 'Kazakhstan', code: 'KZ', vatPrefix: null },
    { name: 'Kenya', code: 'KE', vatPrefix: null },
    { name: 'Kiribati', code: 'KI', vatPrefix: null },
    { name: 'Korea, Democratic People\'S Republic of', code: 'KP', vatPrefix: null },
    { name: 'Korea, Republic of', code: 'KR', vatPrefix: null },
    { name: 'Kuwait', code: 'KW', vatPrefix: null },
    { name: 'Kyrgyzstan', code: 'KG', vatPrefix: null },
    { name: 'Lao People\'S Democratic Republic', code: 'LA', vatPrefix: null },
    { name: 'Latvia', code: 'LV', vatPrefix: 'LV' },
    { name: 'Lebanon', code: 'LB', vatPrefix: null },
    { name: 'Lesotho', code: 'LS', vatPrefix: null },
    { name: 'Liberia', code: 'LR', vatPrefix: null },
    { name: 'Libyan Arab Jamahiriya', code: 'LY', vatPrefix: null },
    { name: 'Liechtenstein', code: 'LI', vatPrefix: null },
    { name: 'Lithuania', code: 'LT', vatPrefix: 'LT' },
    { name: 'Luxembourg', code: 'LU', vatPrefix: 'LU' },
    { name: 'Macao', code: 'MO', vatPrefix: null },
    { name: 'Madagascar', code: 'MG', vatPrefix: null },
    { name: 'Malawi', code: 'MW', vatPrefix: null },
    { name: 'Malaysia', code: 'MY', vatPrefix: null },
    { name: 'Maldives', code: 'MV', vatPrefix: null },
    { name: 'Mali', code: 'ML', vatPrefix: null },
    { name: 'Malta', code: 'MT', vatPrefix: 'MT' },
    { name: 'Marshall Islands', code: 'MH', vatPrefix: null },
    { name: 'Martinique', code: 'MQ', vatPrefix: null },
    { name: 'Mauritania', code: 'MR', vatPrefix: null },
    { name: 'Mauritius', code: 'MU', vatPrefix: null },
    { name: 'Mayotte', code: 'YT', vatPrefix: null },
    { name: 'Mexico', code: 'MX', vatPrefix: null },
    { name: 'Micronesia, Federated States of', code: 'FM', vatPrefix: null },
    { name: 'Moldova, Republic of', code: 'MD', vatPrefix: null },
    { name: 'Monaco', code: 'MC', vatPrefix: null },
    { name: 'Mongolia', code: 'MN', vatPrefix: null },
    { name: 'Montenegro', code: 'ME', vatPrefix: null },
    { name: 'Montserrat', code: 'MS', vatPrefix: null },
    { name: 'Morocco', code: 'MA', vatPrefix: null },
    { name: 'Mozambique', code: 'MZ', vatPrefix: null },
    { name: 'Myanmar', code: 'MM', vatPrefix: null },
    { name: 'Namibia', code: 'NA', vatPrefix: null },
    { name: 'Nauru', code: 'NR', vatPrefix: null },
    { name: 'Nepal', code: 'NP', vatPrefix: null },
    { name: 'Netherlands', code: 'NL', vatPrefix: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN', vatPrefix: null },
    { name: 'New Caledonia', code: 'NC', vatPrefix: null },
    { name: 'New Zealand', code: 'NZ', vatPrefix: null },
    { name: 'Nicaragua', code: 'NI', vatPrefix: null },
    { name: 'Niger', code: 'NE', vatPrefix: null },
    { name: 'Nigeria', code: 'NG', vatPrefix: null },
    { name: 'Niue', code: 'NU', vatPrefix: null },
    { name: 'Norfolk Island', code: 'NF', vatPrefix: null },
    { name: 'North Macedonia', code: 'MK', vatPrefix: null },
    { name: 'Northern Mariana Islands', code: 'MP', vatPrefix: null },
    { name: 'Norway', code: 'NO', vatPrefix: null },
    { name: 'Oman', code: 'OM', vatPrefix: null },
    { name: 'Pakistan', code: 'PK', vatPrefix: null },
    { name: 'Palau', code: 'PW', vatPrefix: null },
    { name: 'Palestinian Territory, Occupied', code: 'PS', vatPrefix: null },
    { name: 'Panama', code: 'PA', vatPrefix: null },
    { name: 'Papua New Guinea', code: 'PG', vatPrefix: null },
    { name: 'Paraguay', code: 'PY', vatPrefix: null },
    { name: 'Peru', code: 'PE', vatPrefix: null },
    { name: 'Philippines', code: 'PH', vatPrefix: null },
    { name: 'Pitcairn', code: 'PN', vatPrefix: null },
    { name: 'Poland', code: 'PL', vatPrefix: 'PL' },
    { name: 'Portugal', code: 'PT', vatPrefix: 'PT' },
    { name: 'Puerto Rico', code: 'PR', vatPrefix: null },
    { name: 'Qatar', code: 'QA', vatPrefix: null },
    { name: 'Reunion', code: 'RE', vatPrefix: null },
    { name: 'Romania', code: 'RO', vatPrefix: 'RO' },
    { name: 'Russian Federation', code: 'RU', vatPrefix: null },
    { name: 'RWANDA', code: 'RW', vatPrefix: null },
    { name: 'Saint Helena', code: 'SH', vatPrefix: null },
    { name: 'Saint Kitts and Nevis', code: 'KN', vatPrefix: null },
    { name: 'Saint Lucia', code: 'LC', vatPrefix: null },
    { name: 'Saint Pierre and Miquelon', code: 'PM', vatPrefix: null },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', vatPrefix: null },
    { name: 'Samoa', code: 'WS', vatPrefix: null },
    { name: 'San Marino', code: 'SM', vatPrefix: null },
    { name: 'Sao Tome and Principe', code: 'ST', vatPrefix: null },
    { name: 'Saudi Arabia', code: 'SA', vatPrefix: null },
    { name: 'Senegal', code: 'SN', vatPrefix: null },
    { name: 'Serbia', code: 'RS', vatPrefix: null },
    { name: 'Seychelles', code: 'SC', vatPrefix: null },
    { name: 'Sierra Leone', code: 'SL', vatPrefix: null },
    { name: 'Singapore', code: 'SG', vatPrefix: null },
    { name: 'Slovakia', code: 'SK', vatPrefix: 'SK' },
    { name: 'Slovenia', code: 'SI', vatPrefix: 'SI' },
    { name: 'Solomon Islands', code: 'SB', vatPrefix: null },
    { name: 'Somalia', code: 'SO', vatPrefix: null },
    { name: 'South Africa', code: 'ZA', vatPrefix: null },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS', vatPrefix: null },
    { name: 'Spain', code: 'ES', vatPrefix: 'ES' },
    { name: 'Sri Lanka', code: 'LK', vatPrefix: null },
    { name: 'Sudan', code: 'SD', vatPrefix: null },
    { name: 'Suriname', code: 'SR', vatPrefix: null },
    { name: 'Svalbard and Jan Mayen', code: 'SJ', vatPrefix: null },
    { name: 'Swaziland', code: 'SZ', vatPrefix: null },
    { name: 'Sweden', code: 'SE', vatPrefix: 'SE' },
    { name: 'Switzerland', code: 'CH', vatPrefix: null },
    { name: 'Syrian Arab Republic', code: 'SY', vatPrefix: null },
    { name: 'Taiwan, Province of China', code: 'TW', vatPrefix: null },
    { name: 'Tajikistan', code: 'TJ', vatPrefix: null },
    { name: 'Tanzania, United Republic of', code: 'TZ', vatPrefix: null },
    { name: 'Thailand', code: 'TH', vatPrefix: null },
    { name: 'Timor-Leste', code: 'TL', vatPrefix: null },
    { name: 'Togo', code: 'TG', vatPrefix: null },
    { name: 'Tokelau', code: 'TK', vatPrefix: null },
    { name: 'Tonga', code: 'TO', vatPrefix: null },
    { name: 'Trinidad and Tobago', code: 'TT', vatPrefix: null },
    { name: 'Tunisia', code: 'TN', vatPrefix: null },
    { name: 'Turkey', code: 'TR', vatPrefix: null },
    { name: 'Turkmenistan', code: 'TM', vatPrefix: null },
    { name: 'Turks and Caicos Islands', code: 'TC', vatPrefix: null },
    { name: 'Tuvalu', code: 'TV', vatPrefix: null },
    { name: 'Uganda', code: 'UG', vatPrefix: null },
    { name: 'Ukraine', code: 'UA', vatPrefix: null },
    { name: 'United Arab Emirates', code: 'AE', vatPrefix: null },
    { name: 'United Kingdom', code: 'GB', vatPrefix: 'GB' },
    { name: 'United States', code: 'US', vatPrefix: null },
    { name: 'United States Minor Outlying Islands', code: 'UM', vatPrefix: null },
    { name: 'Uruguay', code: 'UY', vatPrefix: null },
    { name: 'Uzbekistan', code: 'UZ', vatPrefix: null },
    { name: 'Vanuatu', code: 'VU', vatPrefix: null },
    { name: 'Venezuela', code: 'VE', vatPrefix: null },
    { name: 'Viet Nam', code: 'VN', vatPrefix: null },
    { name: 'Virgin Islands, British', code: 'VG', vatPrefix: null },
    { name: 'Virgin Islands, U.S.', code: 'VI', vatPrefix: null },
    { name: 'Wallis and Futuna', code: 'WF', vatPrefix: null },
    { name: 'Western Sahara', code: 'EH', vatPrefix: null },
    { name: 'Yemen', code: 'YE', vatPrefix: null },
    { name: 'Zambia', code: 'ZM', vatPrefix: null },
    { name: 'Zimbabwe', code: 'ZW', vatPrefix: null }
];


export const europeanCountries: Country[] = countries.filter(country => country.vatPrefix);
